//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaundryManagementSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialUsage
    {
        public int MaterialUsageID { get; set; }
        public int OrderID { get; set; }
        public int MaterialID { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<System.DateTime> UsageDate { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
