//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaundryManagementSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications
    {
        public int NotificationID { get; set; }
        public int OrderID { get; set; }
        public string NotificationType { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public Nullable<bool> IsSent { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
