//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaundryManagementSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.MaterialUsage = new HashSet<MaterialUsage>();
            this.Notifications = new HashSet<Notifications>();
            this.OrderPhotos = new HashSet<OrderPhotos>();
        }
    
        public int OrderID { get; set; }
        public int ClientID { get; set; }
        public int ServiceID { get; set; }
        public int FabricTypeID { get; set; }
        public int StatusID { get; set; }
        public Nullable<bool> Urgent { get; set; }
        public decimal TotalPrice { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string Notes { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual FabricTypes FabricTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialUsage> MaterialUsage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notifications> Notifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPhotos> OrderPhotos { get; set; }
        public virtual OrderStatuses OrderStatuses { get; set; }
        public virtual Services Services { get; set; }
    }
}
