//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaundryManagementSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPhotos
    {
        public int PhotoID { get; set; }
        public int OrderID { get; set; }
        public byte[] PhotoData { get; set; }
        public string PhotoPath { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string Description { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
